### ISSUE TITLE
Style is not applied

### ISSUE THREAD

**Issue by thubtenrigzin** [opipoy/neorg-colors#1]
Hello,

To apply a style within the text, it needs to add a line break after the syntax, otherwise no style is applied :
```
&color:#ffffff
this /text/ is now white

and this /one/ is also white
&color:#ff0000
this /text/ is now blue

this /one/ is also blue
&end_color
this is /now/ regular text. it lookes normal

this is /now/ regular text. it lookes normal
```
Here the result:
![image](https://github.com/user-attachments/assets/f76a16f1-2d7f-4765-8e78-28829f5028ae)

Thanks for this module!

**Comment by opipoy** [comment]
h

**Comment by opipoy** [comment]
hi, thank you for using my plugin, hoping you are enjoying it, i just wanted to know how would you want me to solve this issue, because its not possible to make the &color tag disappear completely, what i thought is that you could write after the tag, like the @color tag, but what do you think?

**Comment by thubtenrigzin** [comment]
I can hide the `&color tag` but the line bellow does not recognize styles... as it should... 
I could eventually use the `@color` which work perfectly but like that I can't use colors for blocks

So the best would be to be able to use style in block with `&color` for all the lines  bellow til the `&end`

Note: I've juste sent you a DM on discord we could speak there if you like

**Comment by thubtenrigzin** [comment]
I've try with the @color but something weird happened

here an example of what I'm trying to do:
![image](https://github.com/user-attachments/assets/edbad8a4-e741-4873-8778-0e49c1411415)
as you can see, I can hide the `&color tag` with conceallevel=2

here with conceallevel=0
![image](https://github.com/user-attachments/assets/75eea936-3769-4f39-a747-0b51f1701543)

so I tried with @color tag instead but something weird happened:
![image](https://github.com/user-attachments/assets/dcdb85d2-ac1c-404a-afc2-3e1a2264aaf8)
even if my conceallevel is set to 2, the link isn't formated correctly, it should only show the description

here with conceallevel=0:
![image](https://github.com/user-attachments/assets/5a6d4feb-6e21-4649-b924-012001466053)
I get an error because of the `@` sign before color...

I don't get it...

anyway, the style works but I get other issues
with conceallevel=2
![image](https://github.com/user-attachments/assets/567d23a9-f443-464a-95da-b528069a99c9)

with conceallevel=0
![image](https://github.com/user-attachments/assets/3d283acb-10db-43b0-ae23-2dbca89236c9)

thanks

**Comment by opipoy** [comment]
ya, now i understand the problem, i will try and find how to fix it, thank you for finding that

**Comment by opipoy** [comment]
i think that you are right, the problem is with the @ key which neorg already uses

**Comment by thubtenrigzin** [comment]
yes I think so, you should maybe use another tag sign...

**Comment by opipoy** [comment]
ok, i think the issue is solved in the development branch, by changing the syntax it should work now
